## О проекте

Проект представляет из себя оверлей с таймерами.
Каждый таймер в списке имеет у себя элементы управления. Стоп и стар, настройки и удаление
У каждого таймера есть модальное окно настроек
под таймерами кнопка добавления таймера

## Стек технологий
- HTML5
- CSS3
- JavaScript
- EmberJs
- Electron
- pods структура

## Директории
`/pods` — папка с описанием контроллеров, роутов и шаблонов - По сути это описание страницы
`/components` — папка компонентами

Остальные директории вспомогательные, создаются при необходимости разработчиком

## Запуск проекта

`yarn start` — запускает EmberJs сервер
`yarn start-electron-app` — запускает дев сервер приложения Electron с предварительно запущенным EmberJs сервером
`yarn electron-pack` — запускает продакшен сборку приложения Electron
